// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPAiLfki49LzaKuW0NJcgxVef-rHmO-X4',
    appId: '1:333380493336:web:b2463ba923c1a53865e36d',
    messagingSenderId: '333380493336',
    projectId: 'reading-books-d328a',
    authDomain: 'reading-books-d328a.firebaseapp.com',
    databaseURL: 'https://reading-books-d328a-default-rtdb.firebaseio.com',
    storageBucket: 'reading-books-d328a.firebasestorage.app',
    measurementId: 'G-DFMRCNKRBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLHihV7SFPmgcdKGFfOAJECoIT2je2xDU',
    appId: '1:333380493336:android:d9982b87fde2ea5d65e36d',
    messagingSenderId: '333380493336',
    projectId: 'reading-books-d328a',
    databaseURL: 'https://reading-books-d328a-default-rtdb.firebaseio.com',
    storageBucket: 'reading-books-d328a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH7uGE_GIna3qVjTQd_P2eGTbGLYK05yU',
    appId: '1:333380493336:ios:67947c8f99fc8def65e36d',
    messagingSenderId: '333380493336',
    projectId: 'reading-books-d328a',
    databaseURL: 'https://reading-books-d328a-default-rtdb.firebaseio.com',
    storageBucket: 'reading-books-d328a.firebasestorage.app',
    iosBundleId: 'com.example.readingBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH7uGE_GIna3qVjTQd_P2eGTbGLYK05yU',
    appId: '1:333380493336:ios:67947c8f99fc8def65e36d',
    messagingSenderId: '333380493336',
    projectId: 'reading-books-d328a',
    databaseURL: 'https://reading-books-d328a-default-rtdb.firebaseio.com',
    storageBucket: 'reading-books-d328a.firebasestorage.app',
    iosBundleId: 'com.example.readingBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPAiLfki49LzaKuW0NJcgxVef-rHmO-X4',
    appId: '1:333380493336:web:1e7957cadd40504765e36d',
    messagingSenderId: '333380493336',
    projectId: 'reading-books-d328a',
    authDomain: 'reading-books-d328a.firebaseapp.com',
    databaseURL: 'https://reading-books-d328a-default-rtdb.firebaseio.com',
    storageBucket: 'reading-books-d328a.firebasestorage.app',
    measurementId: 'G-ZM8JM5TG1X',
  );
}
